#!/usr/bin/env python

import os
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import

import matplotlib.pyplot as plt
import numpy as np
plt.style.use(['seaborn-white', 'seaborn-paper'])
plt.rc("font", family="Times New Roman")

################################################################################
################################################################################
def set_axes_equal(ax):
    '''Make axes of 3D plot have equal scale so that spheres appear as spheres,
    cubes as cubes, etc..  This is one possible solution to Matplotlib's
    ax.set_aspect('equal') and ax.axis('equal') not working for 3D.

    Input
      ax: a matplotlib axis, e.g., as output from plt.gca().
    '''

    x_limits = ax.get_xlim3d()
    y_limits = ax.get_ylim3d()
    z_limits = ax.get_zlim3d()

    x_range = abs(x_limits[1] - x_limits[0])
    x_middle = np.mean(x_limits)
    y_range = abs(y_limits[1] - y_limits[0])
    y_middle = np.mean(y_limits)
    z_range = abs(z_limits[1] - z_limits[0])
    z_middle = np.mean(z_limits)

    # The plot bounding box is a sphere in the sense of the infinity
    # norm, hence I call half the max range the plot radius.
    plot_radius = 0.5*max([x_range, y_range, z_range])

    ax.set_xlim3d([x_middle - plot_radius, x_middle + plot_radius])
    ax.set_ylim3d([y_middle - plot_radius, y_middle + plot_radius])
    ax.set_zlim3d([z_middle - plot_radius, z_middle + plot_radius])

################################################################################
################################################################################

fig = plt.figure()#constrained_layout=True)
ax = fig.gca(projection='3d')
# ax.set_aspect('equal')

# Change working directory to file path
os.chdir(os.path.dirname(os.path.abspath(__file__)))

# Make the grid
R = np.loadtxt("positions.out").T
X,Y,Z = R
MX,MY,MZ = np.loadtxt("magnetization.out").T

R0 = np.sum(R,axis=1)/3
X0,Y0,Z0 = np.array([R0,R0,R0]).T

ax.scatter(X, Y, Z, s=60)
ax.quiver(X, Y, Z, MX, MY, MZ, length=0.5, pivot='middle', color='r')
ax.quiver(X0, Y0, Z0, MX, MY, MZ, length=0.2, pivot='tail', color='k')

ax.set_xlabel(r"$x$", labelpad=13)
ax.set_ylabel(r"$y$", labelpad=13)
ax.set_zlabel(r"$z$", labelpad=7)

plt.tight_layout()
set_axes_equal(ax)
plt.savefig("magnetization.pdf")
plt.show()

