image:
  file: .gitpod.Dockerfile
tasks:
  - init: julia --project=@. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
    command: julia --project=@. -e 'using Pkg; Pkg.activate("."); using LatticeQM'

vscode:
  extensions:
    - julialang.language-julia