image:
  file: .gitpod.Dockerfile
tasks:
  - init: julia -e 'using Pkg; Pkg.develop(path="/workspace/LatticeQM.jl"); using LatticeQM'
    command: julia -e 'using LatticeQM'

vscode:
  extensions:
    - julialang.language-julia