function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    isdefined(LatticeQM.Algebra, Symbol("#10#11")) && precompile(Tuple{getfield(LatticeQM.Algebra, Symbol("#10#11")),Array{Float64,1}})
    isdefined(LatticeQM.Algebra, Symbol("#atK#16")) && precompile(Tuple{getfield(LatticeQM.Algebra, Symbol("#atK#16")),Array{Float64,1}})
    isdefined(LatticeQM.TightBinding, Symbol("#f#32")) && precompile(Tuple{getfield(LatticeQM.TightBinding, Symbol("#f#32")),Array{Float64,1},Array{Complex{Float64},1},Float64})
    isdefined(LatticeQM.TightBinding, Symbol("##gethops#24")) && precompile(Tuple{getfield(LatticeQM.TightBinding, Symbol("##gethops#24")),Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:precision, :format),Tuple{Float64,Symbol}}},typeof(gethops),LatticeQM.Structure.Lattices.Lattice,Array{Array{Int64,1},1},Function})
    isdefined(LatticeQM.TightBinding, Symbol("#f#32")) && precompile(Tuple{getfield(LatticeQM.TightBinding, Symbol("#f#32")),Array{Float64,1},Array{Complex{Float64},1},Complex{Float64}})
    isdefined(LatticeQM.Meanfield, Symbol("##solveselfconsistent!#40")) && precompile(Tuple{getfield(LatticeQM.Meanfield, Symbol("##solveselfconsistent!#40")),Int64,Base.Iterators.Pairs{Symbol,Real,NTuple{6,Symbol},NamedTuple{(:iterations, :tol, :T, :β, :show_trace, :clear_trace),Tuple{Int64,Float64,Float64,Float64,Bool,Bool}}},typeof(LatticeQM.Meanfield.solveselfconsistent!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},AbstractArray{T,2} where T},Function,Function,Float64})
    isdefined(LatticeQM.TightBinding, Symbol("#f#31")) && precompile(Tuple{getfield(LatticeQM.TightBinding, Symbol("#f#31")),Array{Float64,1},Array{Complex{Float64},1},Float64})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Algebra.eigen_sparse)),NamedTuple{(:num_bands,),Tuple{Int64}},typeof(LatticeQM.Algebra.eigen_sparse),SparseArrays.SparseMatrixCSC{Complex{Float64},Int64}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Operators.graphene)),NamedTuple{(:format, :mode, :tz),Tuple{Symbol,Symbol,Float64}},typeof(LatticeQM.Operators.graphene),LatticeQM.Structure.Lattices.Lattice})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Operators.setfilling!)),NamedTuple{(:nk,),Tuple{Int64}},typeof(setfilling!),Dict{Array{Int64,1},AbstractArray{T,2} where T},LatticeQM.Structure.Lattices.Lattice,Float64})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Operators.valleyoperator)),NamedTuple{(:spinhalf,),Tuple{Bool}},typeof(LatticeQM.Operators.valleyoperator),LatticeQM.Structure.Lattices.Lattice})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Spectrum.getbands)),NamedTuple{(:format, :num_bands),Tuple{Symbol,Int64}},typeof(getbands),Dict{Array{Int64,1},AbstractArray{T,2} where T},LatticeQM.Structure.Paths.DiscretePath,Dict{Array{Int64,1},AbstractArray{T,2} where T}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Spectrum.spectrum)),NamedTuple{(:num_bands, :format),Tuple{Int64,Symbol}},typeof(LatticeQM.Spectrum.spectrum),Dict{Array{Int64,1},AbstractArray{T,2} where T}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Structure.Lattices.kpath)),NamedTuple{(:num_points,),Tuple{Int64}},typeof(kpath),LatticeQM.Structure.Lattices.Lattice})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Structure.Paths.path)),NamedTuple{(:B,),Tuple{Transpose{Float64,Array{Float64,2}}}},typeof(LatticeQM.Structure.Paths.path),Array{Array{Float64,1},1},Int64})
    precompile(Tuple{typeof(LatticeQM.Geometries2D.honeycomb_twisted),Int64})
    precompile(Tuple{typeof(LatticeQM.Geometries2D.smoothdisplaceZ!),LatticeQM.Structure.Lattices.Lattice,Float64})
    precompile(Tuple{typeof(LatticeQM.Spectrum.handleprojector),Dict{Array{Int64,1},AbstractArray{T,2} where T}})
    precompile(Tuple{typeof(LatticeQM.Structure.BoundIterator),Array{Tuple{Int64,Int64},2}})
    precompile(Tuple{typeof(addhops!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},SparseArrays.SparseMatrixCSC{Complex{Float64},Int64}}})
    precompile(Tuple{typeof(setfilling!),Dict{Array{Int64,1},AbstractArray{T,2} where T},LatticeQM.Structure.Lattices.Lattice,Array{Float64,2},Float64})
    precompile(Tuple{Core.var"#kw#Type",NamedTuple{(:extradimensions, :specialpoints),Tuple{Array{String,1},LatticeQM.Structure.Paths.LabeledPoints}},Type{LatticeQM.Structure.Lattices.Lattice},Array{Float64,2},Array{Float64,2},Array{Float64,2}})
    precompile(Tuple{typeof(LatticeQM.Geometries2D.honeycomb_twisted),Int64})
    precompile(Tuple{typeof(LatticeQM.Structure.Paths.coordinates2points),Transpose{Float64,Array{Float64,2}},Array{Array{Float64,1},1}})
    precompile(Tuple{typeof(SparseHops),Pair{Array{Int64,1},AbstractArray{T,2} where T},Pair{Array{Int64,1},AbstractArray{T,2} where T},Vararg{Pair{Array{Int64,1},AbstractArray{T,2} where T},N} where N})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Operators.graphene)),NamedTuple{(:mode,),Tuple{Symbol}},typeof(LatticeQM.Operators.graphene),LatticeQM.Structure.Lattices.Lattice})
    precompile(Tuple{typeof(DenseHops),Pair{Array{Int64,1},AbstractArray{T,2} where T},Pair{Array{Int64,1},AbstractArray{T,2} where T},Vararg{Pair{Array{Int64,1},AbstractArray{T,2} where T},N} where N})
    precompile(Tuple{typeof(LatticeQM.Geometries2D.honeycomb)})
    precompile(Tuple{typeof(addhops!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},Array{Complex{Float64},2}}})
    precompile(Tuple{typeof(addzeeman!),Dict{Array{Int64,1},AbstractArray{T,2} where T},LatticeQM.Structure.Lattices.Lattice,Float64})
    precompile(Tuple{typeof(getbands),Dict{Array{Int64,1},AbstractArray{T,2} where T},LatticeQM.Structure.Paths.DiscretePath,Dict{Array{Int64,1},AbstractArray{T,2} where T}})
    precompile(Tuple{typeof(kron),Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Green.densitymatrix!)),NamedTuple{(:T,),Tuple{Float64}},typeof(densitymatrix!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{Float64,1},Array{Complex{Float64},1},Array{Complex{Float64},2}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Green.densitymatrix!)),NamedTuple{(:T,),Tuple{Float64}},typeof(densitymatrix!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{Float64,1},Array{Float64,1},Array{Complex{Float64},2}})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Green.densitymatrix!)),NamedTuple{(:parallel, :T, :format),Tuple{Bool,Float64,Symbol}},typeof(densitymatrix!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{Float64,2},Float64})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Meanfield.gethubbard)),NamedTuple{(:mode, :a, :U),Tuple{Symbol,Float64,Float64}},typeof(gethubbard),LatticeQM.Structure.Lattices.Lattice})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Meanfield.initialguess)),NamedTuple{(:lat,),Tuple{LatticeQM.Structure.Lattices.Lattice}},typeof(initialguess),Dict{Array{Int64,1},AbstractArray{T,2} where T},Symbol})
    precompile(Tuple{Core.kwftype(typeof(LatticeQM.Meanfield.solveselfconsistent!)),NamedTuple{(:iterations, :tol, :T, :β, :show_trace, :clear_trace),Tuple{Int64,Float64,Float64,Float64,Bool,Bool}},typeof(LatticeQM.Meanfield.solveselfconsistent!),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},AbstractArray{T,2} where T},Function,Function,Float64,Array{Float64,2}})
    precompile(Tuple{typeof(LatticeQM.Spectrum.handleprojector),SparseArrays.SparseMatrixCSC{Complex,Int64}})
    precompile(Tuple{typeof(expval),Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{SparseArrays.SparseMatrixCSC{Complex,Int64},1}})
    precompile(Tuple{typeof(getoperator),LatticeQM.Structure.Lattices.Lattice,Array{String,1}})
    precompile(Tuple{typeof(hartreefock),Dict{Array{Int64,1},AbstractArray{T,2} where T},Dict{Array{Int64,1},AbstractArray{T,2} where T}})
    precompile(Tuple{typeof(magnetization),Dict{Array{Int64,1},AbstractArray{T,2} where T},Array{Diagonal{Float64,Array{Float64,1}},1},LatticeQM.Structure.Lattices.Lattice})
end
